### ISSUE TITLE
Allow templated tags

### ISSUE THREAD

**Issue by mtougeron** [mtougeron/k8s-aws-ebs-tagger#15]
Allow setting a tag that uses tpl vars to substitute values from a label or annotation. e.g., `"mytag": "{{ metadata.namespace}}-{{ labels.app }}"` or something like that.

**Comment by bengoldenberg** [comment]
any update with this?

**Comment by mtougeron** [comment]
Honestly I had been waiting to see if there was any real interest in the feature. If there is, I'm happy to work on it. :)

**Comment by bengoldenberg** [comment]
> Honestly I had been waiting to see if there was any real interest in the feature. If there is, I'm happy to work on it. :)

yes i will be happy!
i need to add custom tags. 
moreover, if i understand well, you cant add Name tag for the volume with this tool? i tried to add the Name tag and couldn't do it for some reason, it just jump to the next tag

**Comment by bengoldenberg** [comment]
we will be happy to use' .Values.name ' and those kind of things

**Comment by bengoldenberg** [comment]
do you have any expectation for this?
how long should it take?

**Comment by mtougeron** [comment]
Due to some ongoing family issues my spare time is extremely limited at the moment. I do want to do this but I can't commit to any sort of eta at this time. If I had to hazard a wild guess I'd say sometime in late May.

**Comment by bengoldenberg** [comment]
> Due to some ongoing family issues my spare time is extremely limited at the moment. I do want to do this but I can't commit to any sort of eta at this time. If I had to hazard a wild guess I'd say sometime in late May.

ok all good.
thanks!

**Comment by mtougeron** [comment]
@bengoldenberg I've released the latest version of the app & helm chart with this functionality. Enjoy!

**Comment by bengoldenberg** [comment]
> @bengoldenberg I've released the latest version of the app & helm chart with this functionality. Enjoy!

thanks!
 i will take a look soon and will reply if there will be any problem
