### ISSUE TITLE
Copy tags from EC2 instance

### ISSUE THREAD

**Issue by Giaco9** [mtougeron/k8s-aws-ebs-tagger#26]
**Is your feature request related to a problem? Please describe.**
Would be great to automatically tag volumes with the same or a subset of tags of the instance the ebs is attached to. This would make easier handle tags related for example to cost allocation, business department and so on...

**Comment by mtougeron** [comment]
I had thought about this when I was first thinking about this project. There are a few problems like what to do when the volume changes instances or is not attached to an instance. Also, from a pure PVC/PV perspective it doesn't know if or where it was mounted so there'd have to be an external to k8s watch process to track the cloudwatch events (I think).

If the tags like cost allocation, dept, etc are all static for the cluster/instances, I'd recommend using the `--default-tags` cli option to have them always set on the ebs volume. The annotation on the PVC itself can then override those values if the PVC is for a different cost center.

**Comment by Giaco9** [comment]
Thank you for the clarification!
