### ISSUE TITLE
Add support to specify labels for ServiceMonitor

### ISSUE THREAD

**Issue by sppwf** [mtougeron/k8s-aws-ebs-tagger#35]
**Is your feature request related to a problem? Please describe.**
Yes, Prometheus Operator will read ServiceMonirot resources labeled with sepcifc label, in my case. 

**Describe the solution you'd like**
Add support to specify labels in the helm chart

**Describe alternatives you've considered**
Manualy add those labels

**Comment by mtougeron** [comment]
Thanks for the feature request! I should have time to work on this issue this week. I'll keep you posted about it.
