### ISSUE TITLE
Can't use aws-ebs-tagger/tags annotation got "map", expected "string"

### ISSUE THREAD

**Issue by aleksrosz** [mtougeron/k8s-aws-ebs-tagger#42]
Hi
I have problem that I can't use aws-ebs-tagger/tags annotation. This is my PVC:
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    aws-ebs-tagger/tags: {"me": "someone else", "another tag": "some value"}
  name: foo
spec:
  storageClassName: gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

error: error validating "pvc.yaml": error validating data: ValidationError(PersistentVolumeClaim.metadata.annotations.aws-ebs-tagger/tags): invalid type for io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta.annotations: got "map", expected "string"; if you choose to ignore these errors, turn validation off with --validate=false

It is like there.
https://grepmymind.com/introducing-the-k8s-aws-ebs-tagger-3ec2502cf40e
Maybe something changed? 

Here doc
https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/

**Comment by mtougeron** [comment]
In order for the annotation to be treated as a string it needs to look like:

```
aws-ebs-tagger/tags: |
  {"me": "someone else", "another tag": "some value"}
```

or

```
aws-ebs-tagger/tags: "{\"me\": \"someone else\", \"another tag\": \"some value\"}"
```

**Comment by aleksrosz** [comment]
Yes it works. Thank you.
