### ISSUE TITLE
Cant create Default tags

### ISSUE THREAD

**Issue by bengoldenberg** [mtougeron/k8s-aws-ebs-tagger#43]
when i try to create a volume with Name tag it just ignore the variable and move to the next tag.
is it in purpose? if so can you change it cause this is very valuable tag we need.

**Comment by bengoldenberg** [comment]
> Hi In readme you can see
> 
> https://github.com/mtougeron/k8s-aws-ebs-tagger/blob/main/README.md#ignored-tags

is it possible to change it?
i dont understand the purpose of it

**Comment by mtougeron** [comment]
Let me dbl check my notes on this. I'm pretty sure it was to not conflict with the tags assigned from the ebs controllers (both in-tree & csi).

**Comment by mtougeron** [comment]
Yeah, that was the issue. The aws-ebs-csi-driver already adds the `Name` tag to the EBS volumes. I'm open to the idea of allowing overriding of that value though. 

![image](https://user-images.githubusercontent.com/37266/159528193-f4932875-67e5-4e68-9c09-9062728b02ef.png)

**Comment by bengoldenberg** [comment]
> Yeah, that was the issue. The aws-ebs-csi-driver already adds the `Name` tag to the EBS volumes. I'm open to the idea of allowing overriding of that value though.
> 
> ![image](https://user-images.githubusercontent.com/37266/159528193-f4932875-67e5-4e68-9c09-9062728b02ef.png)

i think it will be great, like to use this tool to tag all, not to use both thing for the same purpose

**Comment by mtougeron** [comment]
Created a PR for this but I'm going to think on the approach overnight. I'll update you tomorrow.

**Comment by bengoldenberg** [comment]
> Created a PR for this but I'm going to think on the approach overnight. I'll update you tomorrow.

great thanks!

**Comment by bengoldenberg** [comment]
<img width="1344" alt="Screen Shot 2022-03-27 at 12 30 08" src="https://user-images.githubusercontent.com/71871067/160275485-29c4cb9b-e3b4-44ff-83fd-32c653c9c6ce.png">
![Screen Shot 2022-03-27 at 12 30 22](https://user-images.githubusercontent.com/71871067/160275488-59963895-513d-43aa-9249-46fb8df5aa00.png)
still doesnt work for me, am i doing something wrong?
also tried with "Name".

**Comment by bengoldenberg** [comment]
![Screen Shot 2022-03-27 at 12 30 22](https://user-images.githubusercontent.com/71871067/160275519-c8955d0c-a40e-4348-b1fa-e395a222f269.png)

**Comment by bengoldenberg** [comment]
@mtougeron FYI

**Comment by mtougeron** [comment]
Did you set the new `--allow-all-tags` flag? In hindsight, I probably should have mentioned that allowing all tags was flagged based.

**Comment by bengoldenberg** [comment]
> Did you set the new `--allow-all-tags` flag? In hindsight, I probably should have mentioned that allowing all tags was flagged based.

no, where should i put it? 
didnt see any info about this flag

**Comment by mtougeron** [comment]
It's a command line flag for the application. If you're using the helm chart, I believe it'd be

```yaml
extraArgs:
  'allow-all-tags': ''
```

**Comment by bengoldenberg** [comment]
> It's a command line flag for the application. If you're using the helm chart, I believe it'd be
> 
> ```yaml
> extraArgs:
>   'allow-all-tags': ''
> ```

where should i put it?
in the vpc i want to tag? in the k8s-aws-ebs-tagger?
can you provide a yaml file for example?

**Comment by mtougeron** [comment]
You would need to create a values file (e.g., `myvalues.yaml`) with the following content:

```yaml
extraArgs:
  'allow-all-tags': ''
```

and when you run `helm install k8s-aws-ebs-tagger --values myvalues.yaml mtougeron/k8s-aws-ebs-tagger`

the deployment would end up looking like:

```yaml
      containers:
        - name: k8s-aws-ebs-tagger
          args:
            - --lease-id=$(POD_NAME)
            - --allow-all-tags
```

**Comment by bengoldenberg** [comment]
> You would need to create a values file (e.g., `myvalues.yaml`) with the following content:
> 
> ```yaml
> extraArgs:
>   'allow-all-tags': ''
> ```
> 
> and when you run `helm install k8s-aws-ebs-tagger --values myvalues.yaml mtougeron/k8s-aws-ebs-tagger`
> 
> the deployment would end up looking like:
> 
> ```yaml
>       containers:
>         - name: k8s-aws-ebs-tagger
>           args:
>             - --lease-id=$(POD_NAME)
>             - --allow-all-tags
> ```

great sir it worked!
thanks alot!!
now i am waiting for the templating part, will be great to use this tool in our envs
